Update package.json
I am not sure this is what cause the error 
but 
npm install component/model throws 
Error: version not found: model : component/model